language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew checkstyle "$MODULE:build"

after_success:
  - ./deploy_snapshot.sh

env:
  matrix:
    - MODULE=circlerefreshlayout
    - MODULE=circlerefreshlayout-rxbinding
    - MODULE=circlerefreshlayout-sample
  global:
    - secure: "y+utgR7k99vqCf8AOKTdORB0oP5ieT1s5iVjD8S10wSjeq55CnH96dJtDLDEA1+1mfwPJF84RD+KJoemQVGP8iULRQhf9vlS0TGmQuydHnX5zK0bUo9NHuQGOlu4OPqNNGgyef69XXA/JQnZ26Gx7nTkdd93gWuGBZI5wmpwd6Bn7TbK7B2S9nJJct+BSHVETm53hNh3NRmXNQyVyd8VPWxaiKfUsUsZH8GWxnZXPmHCuSDuL0ydN9oog2U/Mr1tkaM4ZlPr9GJ70Xuh8rBN2UEVGB6tqvEUCfPLCCtTR4yxSOVOABcHSadb/RtsWQhvgP0pV7YWPpFzL3lJ3nfLpROR59UhDyVQFndcqD6RN+Tj3XofhlMUFopfllPBxD+m311TY5IEYDy2mZ+3KsaCAgIaaheRW5DIMR6cqp/FZ007KMpS4mdiYWCd29oAwK89g5zMu4CVf8eZXC6dZtkRkjHNW520OYAmpcQp7V3UOoj2bnOu6VYmrJSUFIa/qP6ps5gb7QtqwFysLsfSeol1q1cOew5gqHYpTJVDU+Ug7Hbi1/tUY2dizjIBLScmaj9pHIg4Dt4B3flUd0k5/sAvmyO7ecLdo20xDjarH8zRysymzusLSIccdlkTCXDhI/G3ZfKFHEuOQjkcOUXMUGG/JMbIQYyd0tZqDjBj3IbMptg="
    - secure: "RMu2gFDZJqdui5fBDHVhbj711+/Kzsk9G1RaU2oxKjkf0C23LvgFS87BoBLqwaQlpisLr2ewh9n0cO4q9uGRbvYMG9WmmYbF4Fkq3M0fh56LxfJ+b6cO0/F/xpYRX5PDTUGVFYv/PxODElWz1L2RS2FlciNvlF9mWE4yMWSYFleruxv1jwtMm8okHBhG88HVJon1TQS0KJAdHUX6gZJ1pN7kte8gu9/Fh+qiwD8xtAxjjPNlterH9dEUMV7Mr+/Iod7PPtQKX/zGDuFQsBEUImZ8+ohbvv0QGwMpG9mPIgVa6rHyWhJ0U0nNOVJFPo1U7yuqVG+8L18p66+w06o1IQHx1ViyWWvDNtDDkHKlJ8dfqW66HdBTV2Swdw4RRz7VeELqrUM3wTlhhWOq1MgL9dBaIE4Ewt5kQvI0C3WTBVPcNu29ofBBy+GTV6O+XhemArvoSIyPOZnn7VCN3yCBFLU6WTkQPURKutSF6Kmr/Y0HGb0COcbHXOwLpVkic0Ol954LXRtHXwez38M1bB635mTOw6TDufg4unHjgeyY/39zCzMrmZrE/0CqPahzG7BmpolgqhiOd0l6jS5RDAlAIGWDvIbFiRyeHLvIid0OzWonadrnSFdj7sN4viWsvC/0tjSZjsp18k9y9ESRp1NnKjc6KE7DF8QXv5Pn9FSrRJQ="

cache:
  directories:
    - $HOME/.gradle