language: android
sudo: false

android:
  components:
    - build-tools-23.0.3
    - android-23
    - platform-tools
    - tools
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew checkstyle "$MODULE:build"

after_success:
  - .deploy_snapshot.sh

env:
  matrix:
    - MODULE=circlerefreshlayout
    - MODULE=circlerefreshlayout-rxbinding
    - MODULE=circlerefreshlayout-sample

cache:
  directories:
    - $HOME/.gradle